#spring.jpa.defer-datasource-initialization=true
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
      web-allow-others: false

  datasource: 
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    plataform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  #jackson: 
  #  serialization: 
  #    fail-on-empty-beans: false
